### ISSUE TITLE
Not found growpart in CentOS 6.6

### ISSUE THREAD

**Issue by hasonhai** [flegmatik/linux-rootfs-resize#17]
Hi,
I'm trying to use this to make my snapshot's partition "resizable" on an OpenStack platform. Even though I'm using CentOS, the script still looks for "growpart". Growpart is only on Fedora, isn't it?

    [centos@svr01 linux-rootfs-resize-master]$ sudo ./install
    which: no lvs in (/sbin:/bin:/usr/sbin:/usr/bin)
    88621 blocks
    "growpart" not found! Please install
    [centos@svr01 linux-rootfs-resize-master]$ sudo yum install parted
    Loaded plugins: fastestmirror, presto
    Setting up Install Process
    Loading mirror speeds from cached hostfile
     * base: centos.crazyfrogs.org
     * extras: centos.quelquesmots.fr
     * updates: centos.crazyfrogs.org
    Package parted-2.1-25.el6.x86_64 already installed and latest version
    Nothing to do

**Comment by flegmatik** [comment]
You need to install cloud-utils. Growpart is part of that package.

**Comment by hasonhai** [comment]
Thank you!

**Comment by chikatambun** [comment]
i have to do it twice before i get the instance resize disk the flavour of openstack
