### ISSUE TITLE
Support for CentOS/RHEL 7

### ISSUE THREAD

**Issue by jeevers** [flegmatik/linux-rootfs-resize#18]
I have been using this script successfully in EL6, however I am having trouble finding any other utility that provides this functionality in EL7. Is it possible to add support for EL7?

**Comment by jeevers** [comment]
My google-fu was not with me yesterday... The 'cloud-init' package can do the rootfs-resize at boot-time on EL7 (and other distributions).

**Comment by ykfq** [comment]
But `cloud-init` doesn't suppurt to resize LVM based root partition in CentOS 7
